[mypy]
python_version = 3.12
files = main.py, books.py, users.py, logging_config.py
warn_return_any = True
warn_unused_configs = True
disallow_untyped_defs = True
check_untyped_defs = True
no_implicit_optional = True
show_error_codes = True
pretty = True

[mypy-pandas.*]
ignore_missing_imports = False